### ISSUE TITLE
URL with fragment causes error during redirection through authui-container

### ISSUE THREAD

**Issue by neil-williamson** [GoogleCloudPlatform/iap-gcip-web-toolkit#32]
Visiting an IAP-protected URL containing a fragment (something in the shape of https://example.com/#index) causes authui-container to show the message `Cannot read property 'length' of null` and stop processing (at least in `immediateFederatedRedirect` mode).  This doesn't happen once the user is already logged in and therefore does not need to go through the auth UI.

Even if the fragment can't be preserved, it should be possible for the base URL to pass through cleanly with a stripped fragment, as external links or bookmarks may reference the fragment, and shouldn't receive an error message when visited.

**Comment by bojeil-google** [comment]
Hey @neil-williamson, thanks for reporting this. The issue appears to be due to browsers preserving fragments after 302s. We didn't take this behavior into account. We use the fragment as a fallback for older browsers that don't support the history API. We have [fixed](https://github.com/GoogleCloudPlatform/iap-gcip-web-toolkit/releases/tag/v0.1.3) the issue in the underlying `gcip-iap` module.
We have also updated the `authui-container` to use the latest version of that module which has the fix. The instructions to redeploy the container are available [here](https://cloud.google.com/iap/docs/cloud-run-sign-in#redeploy).

You should no longer see the error message after upgrading.
